spring:
  jpa:
    hibernate:
      ddl-auto: create # or create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
logging.level:
  org.hibernate.SQL: off
  com.p6spy: info            # p6spy 로그만 남김